### ISSUE TITLE
Convert to block parser?

### ISSUE THREAD

**Issue by knno** [thephpleague/commonmark-ext-task-list#1]
Hello,
I would like to know if this can be converted to a block parser, to remove or add a class to the **UL** HTML tag in order to remove the bullet point.

- [x] Item 1
- [x] Item 2

Thanks for the ext.

**Comment by colinodell** [comment]
The `[ ]` or `[x]` marker it's looking for is technically an inline element, so for consistency, we should parse it using an inline parser.

That shouldn't prevent you from adding or removing classes though - you could easily [walk through the nodes after they've been parsed](https://commonmark.thephpleague.com/1.0/customization/event-dispatcher/#example), looking for a `TaskListItemMarker`, and updating the relevant ancestor block accordingly.  This would be a much cleaner approach that shouldn't require any workarounds or custom parsers :)
